LibraryWithMVC/Controllers/ShowcaseController.cs
using LibraryWithMVC.Models.Entity;
using System.Linq;
using System.Web.Mvc;
using LibraryWithMVC.Models.MyClasses;

namespace LibraryWithMVC.Controllers
{
    [AllowAnonymous] //Bu controllerda bulunan action'ları authorizationdan muaf tutar
    public class ShowcaseController : Controller
    {
        // GET: Showcase
        [HttpGet]
        public ActionResult Index()
        {
            DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities();

            ViewBag.Title = "Vitrin Paneli";

            Class1 cs = new Class1();
            cs.bookEnumerable = db.tbl_book.ToList();
            cs.aboutEnumerable = db.tbl_about.ToList();

            return View(cs);
        }
        [HttpPost]
        public ActionResult Index(tbl_communication cmm)
        {
            using (DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities())
            {
                ModelState.Remove("cmm_id");
                if (ModelState.IsValid)
                {
                    db.tbl_communication.Add(cmm);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(cmm);
        }

    }
}

LibraryWithMVC/Views/Showcase/Index.cshtml
@model LibraryWithMVC.Models.MyClasses.Class1

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this theme -->
    <link href="/Templates/web/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Lato:400,700,400italic,700italic" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="/Templates/web/css/freelancer.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">Kütüphane Sistemi</a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Kitaplarımız</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">Hakkımızda</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">İletişim</a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/Login/Index/">
                            <i class="fas fa-user fa-lg"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Masthead -->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <img class="masthead-avatar mb-5" src="/Templates/web/img/library.png" alt="">

            <h1 class="masthead-heading text-uppercase mb-0">Kütüphane Sistemi</h1>

            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <p class="masthead-subheading font-weight-light mb-0">Allahım Bana Çiçek Dolu Bir Bahçe ve Kitap Dolu Bir Ev Ver</p>
        </div>
    </header>

    <!-- Portfolio Section -->
    <section class="page-section portfolio" id="portfolio">
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Kitaplarımız</h2>
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="row">
                @foreach (var item in Model.bookEnumerable)
                {
                    <div class="col-md-4 col-lg-3">
                        <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal1">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white">
                                    <i class="fas fa-plus fa-3x"></i>
                                </div>
                            </div>
                            @if (!string.IsNullOrEmpty(item.bk_image))
                            {
                                <img class="img-fluid" src="@item.bk_image" alt="Kitap Resmi">
                            }
                            else
                            {
                                <img class="img-fluid" src="~/Templates/web/img/EmptyBook.png" alt="Varsayılan Kitap Resmi">
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section class="page-section bg-primary text-white mb-0" id="about">
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-white">Hakkımızda</h2>
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="row-cols-1">
                @foreach (var item in Model.aboutEnumerable)
                {
                    <p class="lead">@item.abt_about</p>
                }
            </div>
        </div>
    </section>


    <!-- Contact Section -->
    <section class="page-section" id="contact">
        <div class="container">
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">İletişim</h2>
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    @using (Html.BeginForm("Index", "Showcase", FormMethod.Post))
                    {
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                @Html.Label("cmm_name", "Ad Soyad")
                                @Html.TextBox("cmm_name", null, new { @class = "form-control", placeholder = "Ad Soyad", id = "cmm_name", required = "required" })
                                @Html.ValidationMessage("cmm_name", "", new { @class = "help-block text-danger" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                @Html.Label("cmm_email", "Email Adresi")
                                @Html.TextBox("cmm_email", null, new { @class = "form-control", placeholder = "Email Adresi", id = "cmm_email", type = "email", required = "required" })
                                @Html.ValidationMessage("cmm_email", "", new { @class = "help-block text-danger" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                @Html.Label("cmm_subject", "Konu")
                                @Html.TextBox("cmm_subject", null, new { @class = "form-control", placeholder = "Konu", id = "cmm_subject", required = "required" })
                                @Html.ValidationMessage("cmm_subject", "", new { @class = "help-block text-danger" })
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                @Html.Label("cmm_message", "Mesaj")
                                @Html.TextArea("cmm_message", null, new { @class = "form-control", placeholder = "Mesaj", id = "cmm_message", rows = "5", required = "required" })
                                @Html.ValidationMessage("cmm_message", "", new { @class = "help-block text-danger" })
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="form-group float-right">
                            <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Gönder</button>
                        </div>
                    }

                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Adres</h4>
                    <p class="lead mb-0">
                        İstanbul
                        <br>Türkiye
                    </p>
                </div>
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Bize Ulaş</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="https://www.facebook.com" target="_blank">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="https://x.com/" target="_blank">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="btn btn-outline-light btn-social mx-1" href="https://www.linkedin.com" target="_blank">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Tüm Hakları Saklıdır &copy; Kütüphane Sistemi @(DateTime.Now.Year)</small>
        </div>
    </section>

    <!-- Scroll to Top Button -->
    <div class="scroll-to-top d-lg-none position-fixed">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- Portfolio Modals -->
    <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-labelledby="portfolioModal1Label" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="fas fa-times"></i>
                    </span>
                </button>
                <div class="modal-body text-center">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Log Cabin</h2>
                                <div class="divider-custom">
                                    <div class="divider-custom-line"></div>
                                    <div class="divider-custom-icon">
                                        <i class="fas fa-star"></i>
                                    </div>
                                    <div class="divider-custom-line"></div>
                                </div>
                                <img class="img-fluid rounded mb-5" src="~/Templates/web/img/droxdeney.jpg" alt="">
                                <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>
                                <button class="btn btn-primary" data-dismiss="modal">
                                    <i class="fas fa-times fa-fw"></i>
                                    Pencereyi Kapat
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/Templates/web/vendor/jquery/jquery.min.js"></script>
    <script src="/Templates/web/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="/Templates/web/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="/Templates/web/js/jqBootstrapValidation.js"></script>
    <script src="/Templates/web/js/contact_me.js"></script>

    <!-- Custom scripts for this template -->
    <script src="/Templates/web/js/freelancer.min.js"></script>

</body>

</html>