LibraryWithMVC/Controllers/StaffController.cs
using LibraryWithMVC.Models.Entity;
using System.Linq;
using System.Web.Mvc;

namespace LibraryWithMVC.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff
        public ActionResult Index()
        {
            using (DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities())
            {
                var staff = db.tbl_staff.Where(x => x.stf_status == true).ToList();
                return View(staff);
            }
        }

        // GET: AddStaff
        [HttpGet]
        public ActionResult AddStaff()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddStaff(tbl_staff staff)
        {
            using (DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities())
            {
                ModelState.Remove("stf_id");
                if (ModelState.IsValid)
                {
                    staff.stf_status = true;
                    db.tbl_staff.Add(staff);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(staff);
        }

        //GET: DeleteStaff
        public ActionResult DeleteStaff(int id)
        {
            using (DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities())
            {
                var value = db.tbl_staff.Find(id);
                value.stf_status = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        //GET: EditStaff
        [HttpGet]
        public ActionResult EditStaff(int id)
        {
            using (DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities())
            {
                var value = db.tbl_staff.Where(x => x.stf_status == true).FirstOrDefault(x => x.stf_id == id);
                return View(value);
            }
        }
        [HttpPost]
        public ActionResult EditStaff(tbl_staff staff)
        {
            using (DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities())
            {
                ModelState.Remove("stf_id");
                if (ModelState.IsValid)
                {
                    db.Entry(staff).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(staff);
        }

    }
}

LibraryWithMVC/Views/Staff/AddStaff.cshtml
@model LibraryWithMVC.Models.Entity.tbl_staff

@{
    ViewBag.Title = "Personel Kayıt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Personel Kayıt</h2>
<hr />

@using (Html.BeginForm("AddStaff", "Staff", FormMethod.Post))
{
    @Html.HiddenFor(x => x.stf_id)

    <div class="form-group mt-3">
        @Html.LabelFor(x => x.stf_name, "Personel Adı")
        @Html.TextBoxFor(x => x.stf_name, new { @class = "form-control", @required = "@required" })
        @Html.ValidationMessageFor(x => x.stf_name, "", new { @style = "color:red" })
    </div>

    <div class="form-group mt-3">
        @Html.LabelFor(x => x.stf_surname, "Personel Soyadı")
        @Html.TextBoxFor(x => x.stf_surname, new { @class = "form-control", @required = "@required" })
        @Html.ValidationMessageFor(x => x.stf_surname, "", new { @style = "color:red" })
    </div>

    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary">Ekle</button>
    </div>
}

LibraryWithMVC/Views/Staff/EditStaff.cshtml
@model LibraryWithMVC.Models.Entity.tbl_staff

@{
    ViewBag.Title = "Perseonel Güncelleme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Personel Güncelleme</h2>
<hr />

@using (Html.BeginForm("EditStaff", "Staff", FormMethod.Post))
{
    @Html.HiddenFor(x => x.stf_id)

    <div class="form-group mt-3">
        @Html.LabelFor(x => x.stf_name, "Personel Adı")
        @Html.TextBoxFor(x => x.stf_name, new { @class = "form-control", @required = "@required" })
        @Html.ValidationMessageFor(x => x.stf_name, "", new { @style = "color:red" })
    </div>

    <div class="form-group mt-3">
        @Html.LabelFor(x => x.stf_surname, "Personel Soyadı")
        @Html.TextBoxFor(x => x.stf_surname, new { @class = "form-control", @required = "@required" })
        @Html.ValidationMessageFor(x => x.stf_surname, "", new { @style = "color:red" })
    </div>

    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary">Güncelle</button>
    </div>
}

LibraryWithMVC/Views/Staff/Index.cshtml
@model List<LibraryWithMVC.Models.Entity.tbl_staff>

@{
    ViewBag.Title = "Personeller";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Personel Listesi</h2>
<hr />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Personel Adı</th>
            <th>Personel Soyadı</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.stf_id</td>
                <td>@item.stf_name</td>
                <td>@item.stf_surname</td>
                <td><a href="/Staff/EditStaff/@item.stf_id" class="btn btn-primary">Güncelle</a></td>
                <td>@Html.ActionLink("Sil", "DeleteStaff", new { id = item.stf_id }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstediğinize Emin Misiniz?')" })</td>
            </tr>
        }
    </tbody>
</table>

<a href="/Staff/AddStaff/" class="btn btn-outline-primary">Yeni Personel Ekle</a>