LibraryWithMVC/Controllers/MessageController.cs
using LibraryWithMVC.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace LibraryWithMVC.Controllers
{
    public class MessageController : Controller
    {
        public void getName()
        {
            using (DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities())
            {
                int id = Convert.ToInt32(Session["id"].ToString());
                tbl_member value = db.tbl_member.FirstOrDefault(x => x.mmb_id == id);
                ViewBag.fullname = value.mmb_name + " " + value.mmb_surname;
            }
        }

        // GET: Message
        public ActionResult Index()
        {
            getName();
            DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities();

            int id = (int)Session["id"];
            var values = db.tbl_message.Where(x => x.msg_recipient == id).ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult NewMessage()
        {
            getName();
            DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities();
            List<SelectListItem> members = (from x in db.tbl_member.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.mmb_email,
                                                Value = x.mmb_id.ToString()
                                            }).ToList();
            ViewBag.Recipient = members;
            return View();
        }
        [HttpPost]
        public ActionResult NewMessage(tbl_message msg)
        {
            DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities();
            ModelState.Remove("msg_id");
            if (ModelState.IsValid)
            {
                msg.msg_sender = (int)Session["id"];
                msg.msg_date = DateTime.Now.Date;
                db.tbl_message.Add(msg);
                db.SaveChanges();
                int currentUserId = (int)Session["id"];
                List<tbl_message> messages = db.tbl_message.Where(x => x.msg_recipient == currentUserId).ToList();
                return RedirectToAction("SendMessage", messages);
            }
            return View(msg);

        }

        public ActionResult SendMessage()
        {
            getName();
            DB_LibraryWithMVCEntities db = new DB_LibraryWithMVCEntities();

            int id = (int)Session["id"];
            var values = db.tbl_message.Where(x => x.msg_sender == id).ToList();
            //var values = db.tbl_message
            //                       .Where(x => x.msg_sender == id)
            //                       .Select(x => new
            //                       {
            //                           x.msg_id,
            //                           x.msg_recipient,
            //                           x.msg_subject,
            //                           x.msg_content,
            //                           x.msg_date
            //                       })
            //                       .ToList();
            return View(values);
        }
    }
}

LibraryWithMVC/Views/Message/Index.cshtml
@model List<LibraryWithMVC.Models.Entity.tbl_message>

@{
    ViewBag.Title = "Mesajlar";
    Layout = "~/Views/Shared/_StudentPanelLayout.cshtml";
}

<h2>Mesajlar</h2>
<hr />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Gönderen</th>
            <th>Konu</th>
            <th>Mesaj</th>
            <th>Tarih</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.msg_id</td>
                <td>@item.tbl_member.mmb_email</td>
                <td>@item.msg_subject</td>
                <td>@item.msg_content</td>
                <td>@item.msg_date.Value.ToString("dd MMMM yyyy")</td>
            </tr>
        }
    </tbody>
</table>

<a href="/Message/NewMessage/" class="btn btn-outline-primary">Yeni Mesaj Yaz</a>

LibraryWithMVC/Views/Message/NewMessage.cshtml
@model LibraryWithMVC.Models.Entity.tbl_message
@{
    ViewBag.Title = "Mesaj Gönder";
    Layout = "~/Views/Shared/_StudentPanelLayout.cshtml";
}

<h2>Mesaj Gönder</h2>
<hr />

@using (Html.BeginForm("NewMessage", "Message", FormMethod.Post))
{

    <div class="form-group mt-3">
        @Html.LabelFor(x => x.msg_recipient, "Alıcı")
        @Html.DropDownListFor(x => x.msg_recipient, (List<SelectListItem>)ViewBag.Recipient, new { @class = "form-control", @required = "@required" })
    </div>

    <div class="form-group mt-3">
        @Html.LabelFor(x => x.msg_subject, "Konu")
        @Html.TextBoxFor(x => x.msg_subject, new { @class = "form-control", @required = "@required" })
        @Html.ValidationMessageFor(x => x.msg_subject, "", new { @style = "color:red" })
    </div>

    <div class="form-group mt-3">
        @Html.LabelFor(x => x.msg_content, "Mesaj")
        @Html.TextAreaFor(x => x.msg_content, new { @class = "form-control", rows = "5", @required = "@required" })
        @Html.ValidationMessageFor(x => x.msg_content, "", new { @style = "color:red" })
    </div>

    <div class="form-group mt-3">
        <button type="submit" class="btn btn-success">Gönder</button>
    </div>
}

LibraryWithMVC/Views/Message/SendMessage.cshtml
@model List<LibraryWithMVC.Models.Entity.tbl_message>
@{
    ViewBag.Title = "Gelen Mesajlar";
    Layout = "~/Views/Shared/_StudentPanelLayout.cshtml";
}

<h2>Gelen Mesajlar</h2>
<hr />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Alıcı</th>
            <th>Konu</th>
            <th>Mesaj</th>
            <th>Tarih</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.msg_id</td>
                <td>@item.msg_recipient</td>
                <td>@item.msg_subject</td>
                <td>@item.msg_content</td>
                <td>@item.msg_date.Value.ToString("dd MMMM yyyy")</td>
            </tr>
        }
    </tbody>
</table>